update build-properties

diff --git a/toolchainscripts/build-properties b/toolchainscripts/build-properties
--- a/toolchainscripts/build-properties
+++ b/toolchainscripts/build-properties
@@ -21,5 +21,5 @@ then
   echo "You must create /tools"; exit 1
 fi
 
-#touch "/tools/.test" 2>/dev/null || { echo "Cannot write to /tools"; exit 1; }
-#rm -f "/tools/.test"
+touch "/tools/.test" 2>/dev/null || { echo "Cannot write to /tools"; exit 1; }
+rm -f "/tools/.test"
